title: Taher Chegini
author: Taher Chegini
copyright: "2021"
logo: logo.png

execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/cheginit/personal_website
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true