name: Build and Update The Website

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout personal_website
      uses: actions/checkout@v2
      with:
        path: main
        submodules: recursive

    - name: Checkout cheginit.github.io
      uses: actions/checkout@v2
      with:
        repository: cheginit/cheginit.github.io
        ref: gh-pages
        path: pages
        token: ${{ secrets.JPB_PUSH }}

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -U jupyter-book ghp-import

    - name: Build the website
      run: |-
        cd main
        git submodule update --init
        git submodule update --recursive --remote --merge
        jupyter-book toc from-project personal_website > personal_website/_toc.yml
        jupyter-book build personal_website
        git status -sb
        N_CHANGES=$(git status --porcelain=v1 2>/dev/null | wc -l)
        if [[ $N_CHANGES -gt 0 ]]; then
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "GHW: Fetch updates [skip ci]"
          git push
        fi

    - name: Import contents to gh-pages
      run: |-
        cd pages
        ghp-import -n -p -f ../main/personal_website/_build/html
        git status -sb
        N_CHANGES=$(git status --porcelain=v1 2>/dev/null | wc -l)
        if [[ $N_CHANGES -gt 0 ]]; then
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "GHW: Fetch updates from cheginit/personal_website"
          git push
        fi
